/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Quanser */

#ifndef _Included_Quanser
#define _Included_Quanser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Quanser
 * Method:    connectWrite
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Quanser_connectWrite
  (JNIEnv *, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
